version: "3"
services:
  web:
    build: ./web
    container_name: web
    networks:
      - app-net
    depends_on:
      - redis

  api:
    build: ./api
    container_name: api
    networks:
      - app-net
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /home/ssm-user/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

