name: Android Build & Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 수동으로 워크플로우 실행 가능하게 설정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          tag_name: v${{ github.run_number }}
          name: 병원앱 디버그 빌드 v${{ github.run_number }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/debug/app-debug.apk
          body: |
            자동 빌드된 디버그 APK입니다.
            빌드 시간: ${{ github.event.repository.updated_at }}
            커밋: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
